import unittest
import pexpect

class BankingAutocheck(unittest.TestCase):
    timeout = 3
    def test_age_less_than_12(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('12')
        bank.expect('Customer service: false', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        bank.close()

    def test_bv0_3_03(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('13')
	bank.sendline('99.99')
	bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.03', self.timeout)
        bank.interact()
        bank.close()

    def test_bv0_3_04(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('13')
	bank.sendline('99.98')
	bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.03', self.timeout)
        bank.interact()
        bank.close()

    def test_bv_03_05(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('19')
        bank.sendline('99.98')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.03', self.timeout)
        bank.interact()

    def test_bv_03_06(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('19')
        bank.sendline('99.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.03', self.timeout)
        bank.interact()
       
    def test_bv_03_07(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('13')
        bank.sendline('100.00')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
        
    def test_bv_03_08(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('13')
        bank.sendline('99.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        
    def test_bv_03_09(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('13')
        bank.sendline('99.98')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_10(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('19')
        bank.sendline('99.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_11(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('19')
        bank.sendline('100.00')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_12(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('99.98')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_13(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('99.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_14(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('99.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        
    def test_bv_03_15(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('100.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_16(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('100.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_17(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('499.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        
    def test_bv_03_18(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('499.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_19(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('500.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()

    def test_bv_03_20(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('500.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()        
    
    def test_bv_03_21(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('999.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        
    def test_bv_03_22(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('999.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_23(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('1000.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_24(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('1000.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_25(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('1000.01')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_26(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('20')
        bank.sendline('1000.01')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()

    def test_bv_03_27(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('99.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()

    def test_bv_03_28(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('99.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        
    def test_bv_03_29(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('100.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()        
    
    def test_bv_03_30(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('499.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    

    def test_bv_03_31(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('500.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_32(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('999.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_33(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('1000.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_34(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('1000.01')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_35(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('100.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.01', self.timeout)
        bank.interact()
    
    def test_bv_03_36(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('499.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.01', self.timeout)
        bank.interact()
    
    def test_bv_03_37(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('500.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.05', self.timeout)
        bank.interact()
    
    def test_bv_03_38(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('999.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.05', self.timeout)
        bank.interact()    
    
    def test_bv_03_39(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('1000.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.1', self.timeout)
        bank.interact()
        
    def test_bv_03_40(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('y')
        bank.sendline('1000.01')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: 0.1', self.timeout)
        bank.interact()
    
    def test_bv_03_41(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('99.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_42(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('99.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_43(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('99.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_44(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('99.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_45(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('100.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_46(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('100.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_47(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('100.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_48(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('100.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_49(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('499.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_50(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('499.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_51(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('499.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_52(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('499.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
        
    def test_bv_03_53(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('500.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_54(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('500.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_55(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('500.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_56(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('500.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_57(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('999.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_58(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('999.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_59(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('999.99')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_60(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('999.99')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_61(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('1000.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
        
    def test_bv_03_62(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('1000.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_63(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('1000.00')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()

    def test_bv_03_64(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('1000.00')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()    
    
    def test_bv_03_65(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('1000.01')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_66(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('1000.01')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_67(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('10')
        bank.sendline('1000.01')
        bank.sendline('2')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: true', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    def test_bv_03_68(self):
        bank = pexpect.spawn('ruby run.rb')
        bank.expect(['Banking v0.3', 'Customer age (integer):'], self.timeout)
        bank.sendline('21')
        bank.sendline('n')
        bank.sendline('9')
        bank.sendline('1000.01')
        bank.sendline('3')
        bank.expect('Customer service: true', self.timeout)
        bank.expect('Offer membership: false', self.timeout)
        bank.expect('Discount rate: false', self.timeout)
        bank.interact()
    
    
if __name__ == '__main__':
    unittest.main()


